dockerfile = "Dockerfile"

[identity]
name = "Agent Java"

#[agents."alexey-plotnikoff/agent-java"]
#git = "https://github.com/alexey-plotnikoff/jackin-agent-java.git"
#trusted = true

[claude]
plugins = []
